/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AsterHedgeAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASBNB"
      | "ASBNB_MINTER"
      | "DENOMINATOR"
      | "PANCAKE_ROUTER"
      | "SLISBNB"
      | "USDT"
      | "WBNB"
      | "YIELD_PROXY"
      | "canDeposit"
      | "canWithdraw"
      | "execute"
      | "getAsBnbRate"
      | "getHedgeValue"
      | "getTargetHedgeBps"
      | "hasActiveActivities"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HedgeClosed" | "HedgeOpened" | "HedgeRebalanced"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ASBNB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ASBNB_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PANCAKE_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SLISBNB", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "WBNB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "YIELD_PROXY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAsBnbRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHedgeValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetHedgeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveActivities",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ASBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ASBNB_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PANCAKE_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SLISBNB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "YIELD_PROXY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAsBnbRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHedgeValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetHedgeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveActivities",
    data: BytesLike
  ): Result;
}

export namespace HedgeClosedEvent {
  export type InputTuple = [
    asBnbIn: BigNumberish,
    usdtOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    asBnbIn: bigint,
    usdtOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    asBnbIn: bigint;
    usdtOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HedgeOpenedEvent {
  export type InputTuple = [
    usdtIn: BigNumberish,
    asBnbOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    usdtIn: bigint,
    asBnbOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    usdtIn: bigint;
    asBnbOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HedgeRebalancedEvent {
  export type InputTuple = [oldRatio: BigNumberish, newRatio: BigNumberish];
  export type OutputTuple = [oldRatio: bigint, newRatio: bigint];
  export interface OutputObject {
    oldRatio: bigint;
    newRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AsterHedgeAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): AsterHedgeAdapter;
  waitForDeployment(): Promise<this>;

  interface: AsterHedgeAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASBNB: TypedContractMethod<[], [string], "view">;

  ASBNB_MINTER: TypedContractMethod<[], [string], "view">;

  DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PANCAKE_ROUTER: TypedContractMethod<[], [string], "view">;

  SLISBNB: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  WBNB: TypedContractMethod<[], [string], "view">;

  YIELD_PROXY: TypedContractMethod<[], [string], "view">;

  canDeposit: TypedContractMethod<[], [boolean], "view">;

  canWithdraw: TypedContractMethod<[], [boolean], "view">;

  execute: TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  getAsBnbRate: TypedContractMethod<[], [bigint], "view">;

  getHedgeValue: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getTargetHedgeBps: TypedContractMethod<
    [mode: BigNumberish],
    [bigint],
    "view"
  >;

  hasActiveActivities: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASBNB_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PANCAKE_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SLISBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "YIELD_PROXY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canDeposit"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "canWithdraw"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAsBnbRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHedgeValue"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTargetHedgeBps"
  ): TypedContractMethod<[mode: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasActiveActivities"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "HedgeClosed"
  ): TypedContractEvent<
    HedgeClosedEvent.InputTuple,
    HedgeClosedEvent.OutputTuple,
    HedgeClosedEvent.OutputObject
  >;
  getEvent(
    key: "HedgeOpened"
  ): TypedContractEvent<
    HedgeOpenedEvent.InputTuple,
    HedgeOpenedEvent.OutputTuple,
    HedgeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "HedgeRebalanced"
  ): TypedContractEvent<
    HedgeRebalancedEvent.InputTuple,
    HedgeRebalancedEvent.OutputTuple,
    HedgeRebalancedEvent.OutputObject
  >;

  filters: {
    "HedgeClosed(uint256,uint256,address)": TypedContractEvent<
      HedgeClosedEvent.InputTuple,
      HedgeClosedEvent.OutputTuple,
      HedgeClosedEvent.OutputObject
    >;
    HedgeClosed: TypedContractEvent<
      HedgeClosedEvent.InputTuple,
      HedgeClosedEvent.OutputTuple,
      HedgeClosedEvent.OutputObject
    >;

    "HedgeOpened(uint256,uint256,address)": TypedContractEvent<
      HedgeOpenedEvent.InputTuple,
      HedgeOpenedEvent.OutputTuple,
      HedgeOpenedEvent.OutputObject
    >;
    HedgeOpened: TypedContractEvent<
      HedgeOpenedEvent.InputTuple,
      HedgeOpenedEvent.OutputTuple,
      HedgeOpenedEvent.OutputObject
    >;

    "HedgeRebalanced(uint256,uint256)": TypedContractEvent<
      HedgeRebalancedEvent.InputTuple,
      HedgeRebalancedEvent.OutputTuple,
      HedgeRebalancedEvent.OutputObject
    >;
    HedgeRebalanced: TypedContractEvent<
      HedgeRebalancedEvent.InputTuple,
      HedgeRebalancedEvent.OutputTuple,
      HedgeRebalancedEvent.OutputObject
    >;
  };
}
