/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAsBnbMinterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnAsBnb"
      | "canDeposit"
      | "canWithdraw"
      | "compoundRewards"
      | "convertToAsBnb"
      | "convertToTokens"
      | "minMintAmount"
      | "mintAsBnb(uint256)"
      | "mintAsBnb()"
      | "totalTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burnAsBnb",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "compoundRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToAsBnb",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minMintAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAsBnb(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAsBnb()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokens",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "burnAsBnb", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compoundRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToAsBnb",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minMintAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAsBnb(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAsBnb()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokens",
    data: BytesLike
  ): Result;
}

export interface IAsBnbMinter extends BaseContract {
  connect(runner?: ContractRunner | null): IAsBnbMinter;
  waitForDeployment(): Promise<this>;

  interface: IAsBnbMinterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnAsBnb: TypedContractMethod<
    [amountToBurn: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  canDeposit: TypedContractMethod<[], [boolean], "view">;

  canWithdraw: TypedContractMethod<[], [boolean], "view">;

  compoundRewards: TypedContractMethod<
    [_amountIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  convertToAsBnb: TypedContractMethod<
    [tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertToTokens: TypedContractMethod<
    [asBNBAmount: BigNumberish],
    [bigint],
    "view"
  >;

  minMintAmount: TypedContractMethod<[], [bigint], "view">;

  "mintAsBnb(uint256)": TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "mintAsBnb()": TypedContractMethod<[], [bigint], "payable">;

  totalTokens: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnAsBnb"
  ): TypedContractMethod<[amountToBurn: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "canDeposit"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "canWithdraw"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "compoundRewards"
  ): TypedContractMethod<[_amountIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convertToAsBnb"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToTokens"
  ): TypedContractMethod<[asBNBAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "minMintAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintAsBnb(uint256)"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "mintAsBnb()"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "totalTokens"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
