/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface PancakeSwapFarmAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cakeToken"
      | "execute"
      | "getPendingRewards"
      | "getPoolLPToken"
      | "getStakedAmount"
      | "masterChef"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "EmergencyWithdrawn"
      | "Harvested"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cakeToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRewards",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolLPToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakedAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "masterChef",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cakeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolLPToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "masterChef", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [poolId: bigint, amount: bigint, recipient: string];
  export interface OutputObject {
    poolId: bigint;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawnEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [poolId: bigint, amount: bigint, recipient: string];
  export interface OutputObject {
    poolId: bigint;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    cakeReward: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    poolId: bigint,
    cakeReward: bigint,
    recipient: string
  ];
  export interface OutputObject {
    poolId: bigint;
    cakeReward: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    amount: BigNumberish,
    cakeReward: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    poolId: bigint,
    amount: bigint,
    cakeReward: bigint,
    recipient: string
  ];
  export interface OutputObject {
    poolId: bigint;
    amount: bigint;
    cakeReward: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PancakeSwapFarmAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): PancakeSwapFarmAdapter;
  waitForDeployment(): Promise<this>;

  interface: PancakeSwapFarmAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cakeToken: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  getPendingRewards: TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getPoolLPToken: TypedContractMethod<[poolId: BigNumberish], [string], "view">;

  getStakedAmount: TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  masterChef: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cakeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPendingRewards"
  ): TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolLPToken"
  ): TypedContractMethod<[poolId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStakedAmount"
  ): TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "masterChef"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawn"
  ): TypedContractEvent<
    EmergencyWithdrawnEvent.InputTuple,
    EmergencyWithdrawnEvent.OutputTuple,
    EmergencyWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(uint256,uint256,address)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EmergencyWithdrawn(uint256,uint256,address)": TypedContractEvent<
      EmergencyWithdrawnEvent.InputTuple,
      EmergencyWithdrawnEvent.OutputTuple,
      EmergencyWithdrawnEvent.OutputObject
    >;
    EmergencyWithdrawn: TypedContractEvent<
      EmergencyWithdrawnEvent.InputTuple,
      EmergencyWithdrawnEvent.OutputTuple,
      EmergencyWithdrawnEvent.OutputObject
    >;

    "Harvested(uint256,uint256,address)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "Withdrawn(uint256,uint256,uint256,address)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
