/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EngineCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CYCLE_INTERVAL"
      | "USDF_USDT_PAIR"
      | "canExecuteCycle"
      | "currentMarketMode"
      | "currentRiskScore"
      | "executeCycle"
      | "lastCycleTime"
      | "lastMode"
      | "lastPriceSnapshot"
      | "strategyRouter"
      | "timeUntilNextCycle"
      | "totalCyclesExecuted"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapitalDeployed"
      | "CycleCooldown"
      | "CycleExecuted"
      | "RebalanceTriggered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CYCLE_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDF_USDT_PAIR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canExecuteCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentMarketMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCycleTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastMode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastPriceSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategyRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeUntilNextCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCyclesExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CYCLE_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDF_USDT_PAIR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canExecuteCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentMarketMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCycleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastMode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastPriceSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilNextCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCyclesExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace CapitalDeployedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleCooldownEvent {
  export type InputTuple = [nextCycleTime: BigNumberish];
  export type OutputTuple = [nextCycleTime: bigint];
  export interface OutputObject {
    nextCycleTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleExecutedEvent {
  export type InputTuple = [
    caller: AddressLike,
    mode: BigNumberish,
    riskScore: BigNumberish,
    cycleNumber: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    mode: bigint,
    riskScore: bigint,
    cycleNumber: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    caller: string;
    mode: bigint;
    riskScore: bigint;
    cycleNumber: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceTriggeredEvent {
  export type InputTuple = [mode: BigNumberish, deviationBps: BigNumberish];
  export type OutputTuple = [mode: bigint, deviationBps: bigint];
  export interface OutputObject {
    mode: bigint;
    deviationBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EngineCore extends BaseContract {
  connect(runner?: ContractRunner | null): EngineCore;
  waitForDeployment(): Promise<this>;

  interface: EngineCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CYCLE_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  USDF_USDT_PAIR: TypedContractMethod<[], [string], "view">;

  canExecuteCycle: TypedContractMethod<[], [boolean], "view">;

  currentMarketMode: TypedContractMethod<[], [bigint], "view">;

  currentRiskScore: TypedContractMethod<[], [bigint], "view">;

  executeCycle: TypedContractMethod<[], [void], "nonpayable">;

  lastCycleTime: TypedContractMethod<[], [bigint], "view">;

  lastMode: TypedContractMethod<[], [bigint], "view">;

  lastPriceSnapshot: TypedContractMethod<[], [bigint], "view">;

  strategyRouter: TypedContractMethod<[], [string], "view">;

  timeUntilNextCycle: TypedContractMethod<[], [bigint], "view">;

  totalCyclesExecuted: TypedContractMethod<[], [bigint], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CYCLE_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDF_USDT_PAIR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canExecuteCycle"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "currentMarketMode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeCycle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastCycleTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastMode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPriceSnapshot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "strategyRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timeUntilNextCycle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCyclesExecuted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CapitalDeployed"
  ): TypedContractEvent<
    CapitalDeployedEvent.InputTuple,
    CapitalDeployedEvent.OutputTuple,
    CapitalDeployedEvent.OutputObject
  >;
  getEvent(
    key: "CycleCooldown"
  ): TypedContractEvent<
    CycleCooldownEvent.InputTuple,
    CycleCooldownEvent.OutputTuple,
    CycleCooldownEvent.OutputObject
  >;
  getEvent(
    key: "CycleExecuted"
  ): TypedContractEvent<
    CycleExecutedEvent.InputTuple,
    CycleExecutedEvent.OutputTuple,
    CycleExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceTriggered"
  ): TypedContractEvent<
    RebalanceTriggeredEvent.InputTuple,
    RebalanceTriggeredEvent.OutputTuple,
    RebalanceTriggeredEvent.OutputObject
  >;

  filters: {
    "CapitalDeployed(uint256)": TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;
    CapitalDeployed: TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;

    "CycleCooldown(uint256)": TypedContractEvent<
      CycleCooldownEvent.InputTuple,
      CycleCooldownEvent.OutputTuple,
      CycleCooldownEvent.OutputObject
    >;
    CycleCooldown: TypedContractEvent<
      CycleCooldownEvent.InputTuple,
      CycleCooldownEvent.OutputTuple,
      CycleCooldownEvent.OutputObject
    >;

    "CycleExecuted(address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      CycleExecutedEvent.InputTuple,
      CycleExecutedEvent.OutputTuple,
      CycleExecutedEvent.OutputObject
    >;
    CycleExecuted: TypedContractEvent<
      CycleExecutedEvent.InputTuple,
      CycleExecutedEvent.OutputTuple,
      CycleExecutedEvent.OutputObject
    >;

    "RebalanceTriggered(uint8,uint256)": TypedContractEvent<
      RebalanceTriggeredEvent.InputTuple,
      RebalanceTriggeredEvent.OutputTuple,
      RebalanceTriggeredEvent.OutputObject
    >;
    RebalanceTriggered: TypedContractEvent<
      RebalanceTriggeredEvent.InputTuple,
      RebalanceTriggeredEvent.OutputTuple,
      RebalanceTriggeredEvent.OutputObject
    >;
  };
}
