/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StrategyRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BUFFER_BPS"
      | "BUSD"
      | "DRIFT_THRESHOLD_BPS"
      | "USDF"
      | "USDF_USDT_PAIR"
      | "USDT"
      | "currentMode"
      | "deployCapital"
      | "earnAdapter"
      | "earnAllocationBps"
      | "engineCore"
      | "farmAdapter"
      | "lastPriceSnapshot"
      | "lastSnapshotTime"
      | "lpAdapter"
      | "lpAllocationBps"
      | "rebalance"
      | "riskScore"
      | "totalManagedAssets"
      | "withdrawAssets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CapitalDeployed" | "Rebalanced" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BUFFER_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DRIFT_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDF", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDF_USDT_PAIR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "earnAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "earnAllocationBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "engineCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPriceSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastSnapshotTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpAdapter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lpAllocationBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rebalance", values?: undefined): string;
  encodeFunctionData(functionFragment: "riskScore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalManagedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAssets",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BUFFER_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DRIFT_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDF_USDT_PAIR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earnAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earnAllocationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "engineCore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "farmAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPriceSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSnapshotTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpAdapter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpAllocationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalManagedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAssets",
    data: BytesLike
  ): Result;
}

export namespace CapitalDeployedEvent {
  export type InputTuple = [earnAmount: BigNumberish, lpAmount: BigNumberish];
  export type OutputTuple = [earnAmount: bigint, lpAmount: bigint];
  export interface OutputObject {
    earnAmount: bigint;
    lpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [
    mode: BigNumberish,
    earnBps: BigNumberish,
    lpBps: BigNumberish,
    deviationBps: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    mode: bigint,
    earnBps: bigint,
    lpBps: bigint,
    deviationBps: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    mode: bigint;
    earnBps: bigint;
    lpBps: bigint;
    deviationBps: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [amount: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [amount: bigint, recipient: string];
  export interface OutputObject {
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyRouter extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRouter;
  waitForDeployment(): Promise<this>;

  interface: StrategyRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BUFFER_BPS: TypedContractMethod<[], [bigint], "view">;

  BUSD: TypedContractMethod<[], [string], "view">;

  DRIFT_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  USDF: TypedContractMethod<[], [string], "view">;

  USDF_USDT_PAIR: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  currentMode: TypedContractMethod<[], [bigint], "view">;

  deployCapital: TypedContractMethod<[], [void], "nonpayable">;

  earnAdapter: TypedContractMethod<[], [string], "view">;

  earnAllocationBps: TypedContractMethod<[], [bigint], "view">;

  engineCore: TypedContractMethod<[], [string], "view">;

  farmAdapter: TypedContractMethod<[], [string], "view">;

  lastPriceSnapshot: TypedContractMethod<[], [bigint], "view">;

  lastSnapshotTime: TypedContractMethod<[], [bigint], "view">;

  lpAdapter: TypedContractMethod<[], [string], "view">;

  lpAllocationBps: TypedContractMethod<[], [bigint], "view">;

  rebalance: TypedContractMethod<[], [void], "nonpayable">;

  riskScore: TypedContractMethod<[], [bigint], "view">;

  totalManagedAssets: TypedContractMethod<[], [bigint], "view">;

  withdrawAssets: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BUFFER_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DRIFT_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDF_USDT_PAIR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentMode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deployCapital"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "earnAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "earnAllocationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "engineCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "farmAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastPriceSnapshot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastSnapshotTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lpAllocationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalManagedAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawAssets"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CapitalDeployed"
  ): TypedContractEvent<
    CapitalDeployedEvent.InputTuple,
    CapitalDeployedEvent.OutputTuple,
    CapitalDeployedEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "CapitalDeployed(uint256,uint256)": TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;
    CapitalDeployed: TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;

    "Rebalanced(uint8,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;

    "Withdrawn(uint256,address)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
