/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  YieldOracle,
  YieldOracleInterface,
} from "../../../contracts/libraries/YieldOracle";

const _abi = [
  {
    inputs: [],
    name: "ASUSDF",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ASUSDF_MINTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BUSD",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BUSD_USDT_PAIR",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDF",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDF_MINTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDT",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61019b61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100875760003560e01c80636d950b90116100655780636d950b90146100f9578063a0b03c2614610114578063b249b35d1461012f578063c54e44eb1461014a57600080fd5b8063484f4ea91461008c57806354b0fc7d146100c3578063617ad06d146100de575b600080fd5b6100a773e9e7cea3dedca5984780bafc599bd69add087d5681565b6040516001600160a01b03909116815260200160405180910390f35b6100a773917af46b3c3c6e1bb7286b9f59637fb7c65851fb81565b6100a773db57a53c428a9fafcbfeffb6dd80d0f42754369581565b6100a7737efaef62fddcca950418312c6c91aef321375a0081565b6100a773c271fc70dd9e678ac1ab632f797894fe4be2c34581565b6100a7735a110fc00474038f6c02e89c707d638602ea44b581565b6100a77355d398326f99059ff775485246999027b31979558156fea26469706673582212208ef09a2be57373eae78392161bc39b6989a0a392a0b827c3ebbab44d1bb367b164736f6c63430008140033";

type YieldOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: YieldOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class YieldOracle__factory extends ContractFactory {
  constructor(...args: YieldOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      YieldOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): YieldOracle__factory {
    return super.connect(runner) as YieldOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): YieldOracleInterface {
    return new Interface(_abi) as YieldOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): YieldOracle {
    return new Contract(address, _abi, runner) as unknown as YieldOracle;
  }
}
