/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface YieldOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASUSDF"
      | "ASUSDF_MINTER"
      | "BUSD"
      | "BUSD_USDT_PAIR"
      | "USDF"
      | "USDF_MINTER"
      | "USDT"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ASUSDF", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ASUSDF_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BUSD_USDT_PAIR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDF", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDF_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ASUSDF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ASUSDF_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BUSD_USDT_PAIR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDF_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
}

export interface YieldOracle extends BaseContract {
  connect(runner?: ContractRunner | null): YieldOracle;
  waitForDeployment(): Promise<this>;

  interface: YieldOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASUSDF: TypedContractMethod<[], [string], "view">;

  ASUSDF_MINTER: TypedContractMethod<[], [string], "view">;

  BUSD: TypedContractMethod<[], [string], "view">;

  BUSD_USDT_PAIR: TypedContractMethod<[], [string], "view">;

  USDF: TypedContractMethod<[], [string], "view">;

  USDF_MINTER: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASUSDF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASUSDF_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BUSD_USDT_PAIR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDF_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
