/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IListaStakeManager,
  IListaStakeManagerInterface,
} from "../../../../contracts/adapters/AsterHedgeAdapter.sol/IListaStakeManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "convertBnbToSnBnb",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "convertSnBnbToBnb",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IListaStakeManager__factory {
  static readonly abi = _abi;
  static createInterface(): IListaStakeManagerInterface {
    return new Interface(_abi) as IListaStakeManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IListaStakeManager {
    return new Contract(address, _abi, runner) as unknown as IListaStakeManager;
  }
}
