/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AsterDEXEarnAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASBNB"
      | "ASBNB_MINTER"
      | "ASUSDF"
      | "ASUSDF_MINTER"
      | "DENOMINATOR"
      | "SLISBNB"
      | "USDF"
      | "USDF_MINTER"
      | "USDT"
      | "execute"
      | "getExchangeRate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "WithdrawClaimed"
      | "WithdrawRequested"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ASBNB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ASBNB_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ASUSDF", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ASUSDF_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SLISBNB", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDF", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDF_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ASBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ASBNB_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ASUSDF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ASUSDF_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SLISBNB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDF_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    asset: BigNumberish,
    amountIn: BigNumberish,
    yieldOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    asset: bigint,
    amountIn: bigint,
    yieldOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    asset: bigint;
    amountIn: bigint;
    yieldOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawClaimedEvent {
  export type InputTuple = [
    asset: BigNumberish,
    requestId: BigNumberish,
    underlyingOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    asset: bigint,
    requestId: bigint,
    underlyingOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    asset: bigint;
    requestId: bigint;
    underlyingOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawRequestedEvent {
  export type InputTuple = [
    asset: BigNumberish,
    yieldIn: BigNumberish,
    requester: AddressLike
  ];
  export type OutputTuple = [asset: bigint, yieldIn: bigint, requester: string];
  export interface OutputObject {
    asset: bigint;
    yieldIn: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    asset: BigNumberish,
    yieldIn: BigNumberish,
    underlyingOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    asset: bigint,
    yieldIn: bigint,
    underlyingOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    asset: bigint;
    yieldIn: bigint;
    underlyingOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AsterDEXEarnAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): AsterDEXEarnAdapter;
  waitForDeployment(): Promise<this>;

  interface: AsterDEXEarnAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASBNB: TypedContractMethod<[], [string], "view">;

  ASBNB_MINTER: TypedContractMethod<[], [string], "view">;

  ASUSDF: TypedContractMethod<[], [string], "view">;

  ASUSDF_MINTER: TypedContractMethod<[], [string], "view">;

  DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  SLISBNB: TypedContractMethod<[], [string], "view">;

  USDF: TypedContractMethod<[], [string], "view">;

  USDF_MINTER: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [arg0: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  getExchangeRate: TypedContractMethod<[asset: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASBNB_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASUSDF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASUSDF_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLISBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDF_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [arg0: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getExchangeRate"
  ): TypedContractMethod<[asset: BigNumberish], [bigint], "view">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawClaimed"
  ): TypedContractEvent<
    WithdrawClaimedEvent.InputTuple,
    WithdrawClaimedEvent.OutputTuple,
    WithdrawClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawRequested"
  ): TypedContractEvent<
    WithdrawRequestedEvent.InputTuple,
    WithdrawRequestedEvent.OutputTuple,
    WithdrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(uint8,uint256,uint256,address)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "WithdrawClaimed(uint8,uint256,uint256,address)": TypedContractEvent<
      WithdrawClaimedEvent.InputTuple,
      WithdrawClaimedEvent.OutputTuple,
      WithdrawClaimedEvent.OutputObject
    >;
    WithdrawClaimed: TypedContractEvent<
      WithdrawClaimedEvent.InputTuple,
      WithdrawClaimedEvent.OutputTuple,
      WithdrawClaimedEvent.OutputObject
    >;

    "WithdrawRequested(uint8,uint256,address)": TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
    WithdrawRequested: TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;

    "Withdrawn(uint8,uint256,uint256,address)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
