/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  VolatilityLib,
  VolatilityLibInterface,
} from "../../../../contracts/libraries/VolatilityLib.sol/VolatilityLib";

const _abi = [
  {
    inputs: [],
    name: "DRAWDOWN_EARN_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DRAWDOWN_THRESHOLD_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NORMAL_EARN_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VOLATILE_EARN_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VOLATILE_THRESHOLD_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60d0610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610605b5760003560e01c80631cedddec1460605780633e43b76814607a5780634d83f26d14608257806352e7103914608a57806360ad133e146092575b600080fd5b60686101f481565b60405190815260200160405180910390f35b606861177081565b606861232881565b606861012c81565b6068611f408156fea2646970667358221220bfce536ea893e31ed351e2507a4b35c601288c48eb5025d145f30be242e66b5864736f6c63430008140033";

type VolatilityLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VolatilityLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VolatilityLib__factory extends ContractFactory {
  constructor(...args: VolatilityLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VolatilityLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VolatilityLib__factory {
    return super.connect(runner) as VolatilityLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VolatilityLibInterface {
    return new Interface(_abi) as VolatilityLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VolatilityLib {
    return new Contract(address, _abi, runner) as unknown as VolatilityLib;
  }
}
