/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface VolatilityLibInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DRAWDOWN_EARN_BPS"
      | "DRAWDOWN_THRESHOLD_BPS"
      | "NORMAL_EARN_BPS"
      | "VOLATILE_EARN_BPS"
      | "VOLATILE_THRESHOLD_BPS"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DRAWDOWN_EARN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DRAWDOWN_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NORMAL_EARN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOLATILE_EARN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOLATILE_THRESHOLD_BPS",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DRAWDOWN_EARN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DRAWDOWN_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NORMAL_EARN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOLATILE_EARN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOLATILE_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
}

export interface VolatilityLib extends BaseContract {
  connect(runner?: ContractRunner | null): VolatilityLib;
  waitForDeployment(): Promise<this>;

  interface: VolatilityLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DRAWDOWN_EARN_BPS: TypedContractMethod<[], [bigint], "view">;

  DRAWDOWN_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  NORMAL_EARN_BPS: TypedContractMethod<[], [bigint], "view">;

  VOLATILE_EARN_BPS: TypedContractMethod<[], [bigint], "view">;

  VOLATILE_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DRAWDOWN_EARN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DRAWDOWN_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NORMAL_EARN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOLATILE_EARN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOLATILE_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
