/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4626__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC4626__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "AsterDEXEarnAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AsterDEXEarnAdapter__factory>;
    getContractFactory(
      name: "IMinterAster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterAster__factory>;
    getContractFactory(
      name: "ISimpleEarn",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISimpleEarn__factory>;
    getContractFactory(
      name: "AsterHedgeAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AsterHedgeAdapter__factory>;
    getContractFactory(
      name: "IAsBnbMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAsBnbMinter__factory>;
    getContractFactory(
      name: "IListaStakeManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IListaStakeManager__factory>;
    getContractFactory(
      name: "IPancakeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeRouter__factory>;
    getContractFactory(
      name: "IYieldProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IYieldProxy__factory>;
    getContractFactory(
      name: "IMasterChefV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMasterChefV2__factory>;
    getContractFactory(
      name: "PancakeSwapFarmAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PancakeSwapFarmAdapter__factory>;
    getContractFactory(
      name: "IPancakeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeFactory__factory>;
    getContractFactory(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakePair__factory>;
    getContractFactory(
      name: "IPancakeRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeRouter02__factory>;
    getContractFactory(
      name: "PancakeSwapV2LPAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PancakeSwapV2LPAdapter__factory>;
    getContractFactory(
      name: "EngineCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EngineCore__factory>;
    getContractFactory(
      name: "MetaVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MetaVault__factory>;
    getContractFactory(
      name: "IAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAdapter__factory>;
    getContractFactory(
      name: "IMasterChefV2View",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMasterChefV2View__factory>;
    getContractFactory(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakePair__factory>;
    getContractFactory(
      name: "IPancakeRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeRouter02__factory>;
    getContractFactory(
      name: "ISimpleEarnView",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISimpleEarnView__factory>;
    getContractFactory(
      name: "MetaYieldVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MetaYieldVault__factory>;
    getContractFactory(
      name: "StrategyRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StrategyRouter__factory>;
    getContractFactory(
      name: "IAsterPerp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAsterPerp__factory>;
    getContractFactory(
      name: "VaultMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultMath__factory>;
    getContractFactory(
      name: "IPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPair__factory>;
    getContractFactory(
      name: "VolatilityLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VolatilityLib__factory>;
    getContractFactory(
      name: "YieldOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldOracle__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4626>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC4626>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "AsterDEXEarnAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AsterDEXEarnAdapter>;
    getContractAt(
      name: "IMinterAster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMinterAster>;
    getContractAt(
      name: "ISimpleEarn",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISimpleEarn>;
    getContractAt(
      name: "AsterHedgeAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AsterHedgeAdapter>;
    getContractAt(
      name: "IAsBnbMinter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAsBnbMinter>;
    getContractAt(
      name: "IListaStakeManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IListaStakeManager>;
    getContractAt(
      name: "IPancakeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeRouter>;
    getContractAt(
      name: "IYieldProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IYieldProxy>;
    getContractAt(
      name: "IMasterChefV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMasterChefV2>;
    getContractAt(
      name: "PancakeSwapFarmAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PancakeSwapFarmAdapter>;
    getContractAt(
      name: "IPancakeFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeFactory>;
    getContractAt(
      name: "IPancakePair",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakePair>;
    getContractAt(
      name: "IPancakeRouter02",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeRouter02>;
    getContractAt(
      name: "PancakeSwapV2LPAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PancakeSwapV2LPAdapter>;
    getContractAt(
      name: "EngineCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EngineCore>;
    getContractAt(
      name: "MetaVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MetaVault>;
    getContractAt(
      name: "IAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAdapter>;
    getContractAt(
      name: "IMasterChefV2View",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMasterChefV2View>;
    getContractAt(
      name: "IPancakePair",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakePair>;
    getContractAt(
      name: "IPancakeRouter02",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeRouter02>;
    getContractAt(
      name: "ISimpleEarnView",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISimpleEarnView>;
    getContractAt(
      name: "MetaYieldVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MetaYieldVault>;
    getContractAt(
      name: "StrategyRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StrategyRouter>;
    getContractAt(
      name: "IAsterPerp",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAsterPerp>;
    getContractAt(
      name: "VaultMath",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultMath>;
    getContractAt(
      name: "IPair",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPair>;
    getContractAt(
      name: "VolatilityLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VolatilityLib>;
    getContractAt(
      name: "YieldOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldOracle>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC4626>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AsterDEXEarnAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AsterDEXEarnAdapter>;
    deployContract(
      name: "IMinterAster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMinterAster>;
    deployContract(
      name: "ISimpleEarn",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISimpleEarn>;
    deployContract(
      name: "AsterHedgeAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AsterHedgeAdapter>;
    deployContract(
      name: "IAsBnbMinter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAsBnbMinter>;
    deployContract(
      name: "IListaStakeManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IListaStakeManager>;
    deployContract(
      name: "IPancakeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter>;
    deployContract(
      name: "IYieldProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldProxy>;
    deployContract(
      name: "IMasterChefV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterChefV2>;
    deployContract(
      name: "PancakeSwapFarmAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeSwapFarmAdapter>;
    deployContract(
      name: "IPancakeFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeFactory>;
    deployContract(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter02",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter02>;
    deployContract(
      name: "PancakeSwapV2LPAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeSwapV2LPAdapter>;
    deployContract(
      name: "EngineCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EngineCore>;
    deployContract(
      name: "MetaVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MetaVault>;
    deployContract(
      name: "IAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAdapter>;
    deployContract(
      name: "IMasterChefV2View",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterChefV2View>;
    deployContract(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter02",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter02>;
    deployContract(
      name: "ISimpleEarnView",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISimpleEarnView>;
    deployContract(
      name: "MetaYieldVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MetaYieldVault>;
    deployContract(
      name: "StrategyRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StrategyRouter>;
    deployContract(
      name: "IAsterPerp",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAsterPerp>;
    deployContract(
      name: "VaultMath",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultMath>;
    deployContract(
      name: "IPair",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPair>;
    deployContract(
      name: "VolatilityLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VolatilityLib>;
    deployContract(
      name: "YieldOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOracle>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC4626>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AsterDEXEarnAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AsterDEXEarnAdapter>;
    deployContract(
      name: "IMinterAster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMinterAster>;
    deployContract(
      name: "ISimpleEarn",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISimpleEarn>;
    deployContract(
      name: "AsterHedgeAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AsterHedgeAdapter>;
    deployContract(
      name: "IAsBnbMinter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAsBnbMinter>;
    deployContract(
      name: "IListaStakeManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IListaStakeManager>;
    deployContract(
      name: "IPancakeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter>;
    deployContract(
      name: "IYieldProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldProxy>;
    deployContract(
      name: "IMasterChefV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterChefV2>;
    deployContract(
      name: "PancakeSwapFarmAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeSwapFarmAdapter>;
    deployContract(
      name: "IPancakeFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeFactory>;
    deployContract(
      name: "IPancakePair",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter02",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter02>;
    deployContract(
      name: "PancakeSwapV2LPAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeSwapV2LPAdapter>;
    deployContract(
      name: "EngineCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EngineCore>;
    deployContract(
      name: "MetaVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MetaVault>;
    deployContract(
      name: "IAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAdapter>;
    deployContract(
      name: "IMasterChefV2View",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterChefV2View>;
    deployContract(
      name: "IPancakePair",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter02",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter02>;
    deployContract(
      name: "ISimpleEarnView",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISimpleEarnView>;
    deployContract(
      name: "MetaYieldVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MetaYieldVault>;
    deployContract(
      name: "StrategyRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StrategyRouter>;
    deployContract(
      name: "IAsterPerp",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAsterPerp>;
    deployContract(
      name: "VaultMath",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultMath>;
    deployContract(
      name: "IPair",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPair>;
    deployContract(
      name: "VolatilityLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VolatilityLib>;
    deployContract(
      name: "YieldOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOracle>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
